version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://cloudedze_user:cloudedze_password@db:5432/cloudedze
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cloudedze
      - POSTGRES_USER=cloudedze_user
      - POSTGRES_PASSWORD=cloudedze_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudedze_user -d cloudedze"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: