#!/bin/bash

echo "🔧 Manual Server Fix Commands"
echo "=============================="
echo ""
echo "The error is happening because the compiled JavaScript in dist/ is outdated."
echo "You need to update the source files and rebuild the application."
echo ""
echo "📋 Commands to run on your server (34.14.198.14):"
echo ""
echo "1. First, connect to your server:"
echo "   ssh santosh@34.14.198.14"
echo ""
echo "2. Navigate to your project directory:"
echo "   cd /home/santosh/cloudedze"
echo ""
echo "3. Stop the current application:"
echo "   pm2 stop cloudedze"
echo ""
echo "4. Update the Python script:"
echo "   # Copy the updated Python script from your local machine:"
echo "   # (Run this from your local machine):"
echo "   scp server/services/python-scripts/oci-inventory.py santosh@34.14.198.14:/home/santosh/cloudedze/server/services/python-scripts/oci-inventory.py"
echo ""
echo "5. Update the TypeScript service:"
echo "   # Copy the updated TypeScript service from your local machine:"
echo "   # (Run this from your local machine):"
echo "   scp server/services/oci-inventory.ts santosh@34.14.198.14:/home/santosh/cloudedze/server/services/oci-inventory.ts"
echo ""
echo "6. Set proper permissions:"
echo "   chmod +x server/services/python-scripts/oci-inventory.py"
echo ""
echo "7. Install dependencies (if needed):"
echo "   npm install"
echo ""
echo "8. Build the application (THIS IS CRITICAL):"
echo "   npm run build"
echo ""
echo "9. Start the application:"
echo "   pm2 start ecosystem.config.js --name cloudedze"
echo ""
echo "10. Save PM2 configuration:"
echo "    pm2 save"
echo ""
echo "🎯 The key step is #8 - 'npm run build'"
echo "   This will compile the fixed TypeScript code into the dist/ folder"
echo "   and resolve the 'result is not defined' error."
echo ""
echo "📊 After rebuilding, your OCI inventory should discover many more resources!"
echo ""
echo "🔍 To verify the fix worked:"
echo "1. Check PM2 logs: pm2 logs cloudedze"
echo "2. Run an inventory scan in your application"
echo "3. Look for detailed resource discovery in the logs"
echo ""
echo "✅ This will fix the ReferenceError and enable full OCI resource discovery!"
