#!/bin/bash

echo "🔧 Server Fix Commands"
echo "======================"
echo ""
echo "Run these commands on your server (34.14.198.14) to fix the ReferenceError:"
echo ""
echo "1. Connect to your server:"
echo "   ssh santosh@34.14.198.14"
echo ""
echo "2. Navigate to your project:"
echo "   cd /home/santosh/cloudedze"
echo ""
echo "3. Stop the application:"
echo "   pm2 stop cloudedze"
echo ""
echo "4. Create backup of current files:"
echo "   cp server/services/oci-inventory.ts server/services/oci-inventory.ts.backup"
echo "   cp server/services/python-scripts/oci-inventory.py server/services/python-scripts/oci-inventory.py.backup"
echo ""
echo "5. Download the fixed TypeScript file:"
echo "   curl -o server/services/oci-inventory.ts https://raw.githubusercontent.com/your-repo/cloudedze/main/server/services/oci-inventory.ts"
echo ""
echo "6. Download the fixed Python script:"
echo "   curl -o server/services/python-scripts/oci-inventory.py https://raw.githubusercontent.com/your-repo/cloudedze/main/server/services/python-scripts/oci-inventory.py"
echo ""
echo "7. Set proper permissions:"
echo "   chmod +x server/services/python-scripts/oci-inventory.py"
echo ""
echo "8. Install dependencies:"
echo "   npm install"
echo ""
echo "9. Build the application (CRITICAL!):"
echo "   npm run build"
echo ""
echo "10. Start the application:"
echo "    pm2 start ecosystem.config.js --name cloudedze"
echo ""
echo "11. Save PM2 configuration:"
echo "    pm2 save"
echo ""
echo "12. Check logs:"
echo "    pm2 logs cloudedze"
echo ""
echo "🎯 The key step is #9 - 'npm run build'"
echo "   This compiles the fixed TypeScript code and resolves the ReferenceError"
echo ""
echo "✅ After this, your OCI inventory should discover all resources!"
