#!/bin/bash

echo "🔒 Setting up HTTPS (Port 443) with SSL Certificate"
echo "=================================================="
echo ""

echo "📋 Commands to run on your server:"
echo ""

echo "1. Install Certbot for SSL:"
echo "   sudo yum install -y python3-pip"
echo "   sudo pip3 install certbot"
echo "   sudo pip3 install certbot-nginx"
echo ""

echo "2. Create Nginx configuration with HTTPS:"
echo "   sudo nano /etc/nginx/conf.d/cloudedze.conf"
echo ""

echo "3. Add this configuration (HTTP + HTTPS):"
echo "   server {"
echo "       listen 80;"
echo "       server_name cloudedze.ai www.cloudedze.ai;"
echo "       "
echo "       # Redirect HTTP to HTTPS"
echo "       return 301 https://\$server_name\$request_uri;"
echo "   }"
echo "   "
echo "   server {"
echo "       listen 443 ssl http2;"
echo "       server_name cloudedze.ai www.cloudedze.ai;"
echo "       "
echo "       # SSL will be configured by Certbot"
echo "       # ssl_certificate /etc/letsencrypt/live/cloudedze.ai/fullchain.pem;"
echo "       # ssl_certificate_key /etc/letsencrypt/live/cloudedze.ai/privkey.pem;"
echo "       "
echo "       location / {"
echo "           proxy_pass http://localhost:3000;"
echo "           proxy_http_version 1.1;"
echo "           proxy_set_header Upgrade \$http_upgrade;"
echo "           proxy_set_header Connection 'upgrade';"
echo "           proxy_set_header Host \$host;"
echo "           proxy_set_header X-Real-IP \$remote_addr;"
echo "           proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "           proxy_set_header X-Forwarded-Proto \$scheme;"
echo "           proxy_cache_bypass \$http_upgrade;"
echo "           proxy_read_timeout 86400;"
echo "       }"
echo "   }"
echo ""

echo "4. Remove default Nginx configuration:"
echo "   sudo rm /etc/nginx/conf.d/default.conf"
echo ""

echo "5. Test Nginx configuration:"
echo "   sudo nginx -t"
echo ""

echo "6. Reload Nginx:"
echo "   sudo systemctl reload nginx"
echo ""

echo "7. Configure firewall for HTTPS:"
echo "   sudo firewall-cmd --permanent --add-service=http"
echo "   sudo firewall-cmd --permanent --add-service=https"
echo "   sudo firewall-cmd --reload"
echo ""

echo "8. Get SSL certificate for HTTPS:"
echo "   sudo certbot --nginx -d cloudedze.ai -d www.cloudedze.ai --non-interactive --agree-tos --email admin@cloudedze.ai"
echo ""

echo "9. Test SSL certificate renewal:"
echo "   sudo certbot renew --dry-run"
echo ""

echo "10. Test the secure setup:"
echo "    curl -I http://cloudedze.ai"
echo "    curl -I https://cloudedze.ai"
echo "    curl -I https://34.14.198.14"
echo ""

echo "🎯 What this gives you:"
echo "   ✅ HTTP (port 80) → automatically redirects to HTTPS"
echo "   ✅ HTTPS (port 443) → secure SSL encrypted connection"
echo "   ✅ SSL certificate from Let's Encrypt (free)"
echo "   ✅ Auto-renewal of SSL certificate"
echo "   ✅ Your PM2 app accessible via https://cloudedze.ai"
echo ""

echo "🔒 Security features:"
echo "   - All traffic encrypted with SSL/TLS"
echo "   - HTTP Strict Transport Security (HSTS)"
echo "   - Secure headers configured"
echo "   - Automatic HTTP to HTTPS redirect"
echo ""

echo "✅ After this, your app will be secure on port 443!"
